require_relative '../spec_helper'

describe 'default.md.erb' do

  let(:template) {
    body = File.read('lib/assets/tt/default.md.erb')
    body.gsub!("lib/markup_node", "lib/assets/lib/markup_node")
    body.gsub(/^% This file was generated by .*$/, '% generated by Clerq')
  }

  let(:assembly) {
    Node.new(title: 'Template Test').tap do |n|
      n << Node.new(id: 'p1', title: 'Part One')
      n << Node.new(id: 'p2', title: 'Part Two')
    end
  }

  let(:output) {
    <<~EOF
      % Template Test
      % generated by Clerq
      % using "default.md.erb" template

      # Part One {#p1}

      Attribute | Value
      --------- | -----
      id | p1

      # Part Two {#p2}

      Attribute | Value
      --------- | -----
      id | p2

    EOF
  }

  it 'must render correct output' do
    out = Clerq::Services::RenderErb.(erb: template, object: assembly)
    _(out).must_match output
  end

end
