require_relative 'repositories/repository'
require_relative 'repositories/in_memory'
require_relative 'repositories/node_reader'
require_relative 'repositories/node_repository'
require_relative 'repositories/template_repository'
